INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (1,"3452",now(),"MAZDA LOGISTICA",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (2,"3380",now(),"DECOPLAS",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (3,"3388",now(),"MAZDA",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (4,"3401",now(),"HIROTEC",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (5,"3413",now(),"AUDI",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (6,"3424",now(),"MENTEC",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (7,"3435",now(),"NAVISTAR",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (8,"3436",now(),"Jatco 1",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (9,"0001",now(),"Jatco 2",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (10,"3441",now(),"TRUPER",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (11,"3444",now(),"MAZDA LOGISTICA",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (12,"3446",now(),"SIGNA",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (13,"3459",now(),"BMW",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (14,"3462",now(),"TOYOTA",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (15,"3463",now(),"COMPAS",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (16,"3466",now(),"HELLA IRAPUATO",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (17,"3476",now(),"GOODYEAR",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (18,"3477",now(),"GB",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (19,"3479",now(),"MARELLI",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (20,"3480",now(),"Avanzar",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (21,"3486",now(),"STELLANTIS",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (22,"3490",now(),"ANTOLIN TOLUCA",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (23,"3497",now(),"CONMET",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (24,"3900",now(),"SAINT GOBAIN",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (25,"3468CYA",now(),"MABE CELAYA",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (26,"3468SLP",now(),"MABE SLP",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (27,"GISA",now(),"GISA",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (28,"GMTOL",now(),"GM TOLUCA",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (29,"VW",now(),"VW",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (30,"USIADI",now(),"ADIENT",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (31,"3433",now(),"AGC, SLP.",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (32,"0002",now(),"FAURECIA",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (33,"0003",now(),"FAURECIA, FAURECIA FRAMES, FAURECIA MECANISMOS",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (34,"USIFORDCH",now(),"FORD CHIHUAHUA",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (35,"USIFORDCU",now(),"FORD CUAUTITLAN",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (36,"3468SAL",now(),"MABE SALTILLO",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (37,"3903",now(),"MANDO CORP",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (38,"3348",now(),"PEMSA",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (39,"USIZFM",now(),"ZF EL MARQUEZ",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (40,"USIZFSR",now(),"ZF EL MARQUEZ, ZF STA ROSA",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (41,"0004",now(),"ZF SANTA ROSA",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (42,"3411SLP",now(),"FAURECIA FRAMES",1,1);
INSERT INTO `cliente`(id_cliente ,`clave_cln`, `fecha_alta_cln`, `nombre_cln`, `estado_cln_id_estado`, `id_usuario_cln_id_usuario`) VALUES (43,"3411",now(),"FAURECIA MECANISMOS",1,1);
