INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (1,'3452',GETDATE(),'MAZDA LOGISTICA',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (2,'3380',GETDATE(),'DECOPLAS',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (3,'3388',GETDATE(),'MAZDA',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (4,'3401',GETDATE(),'HIROTEC',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (5,'3413',GETDATE(),'AUDI',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (6,'3424',GETDATE(),'MENTEC',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (7,'3435',GETDATE(),'NAVISTAR',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (8,'3436',GETDATE(),'Jatco 1',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (9,'0001',GETDATE(),'Jatco 2',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (10,'3441',GETDATE(),'TRUPER',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (11,'3444',GETDATE(),'MAZDA LOGISTICA',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (12,'3446',GETDATE(),'SIGNA',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (13,'3459',GETDATE(),'BMW',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (14,'3462',GETDATE(),'TOYOTA',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (15,'3463',GETDATE(),'COMPAS',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (16,'3466',GETDATE(),'HELLA IRAPUATO',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (17,'3476',GETDATE(),'GOODYEAR',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (18,'3477',GETDATE(),'GB',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (19,'3479',GETDATE(),'MARELLI',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (20,'3480',GETDATE(),'Avanzar',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (21,'3486',GETDATE(),'STELLANTIS',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (22,'3490',GETDATE(),'ANTOLIN TOLUCA',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (23,'3497',GETDATE(),'CONMET',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (24,'3900',GETDATE(),'SAINT GOBAIN',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (25,'3468CYA',GETDATE(),'MABE CELAYA',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (26,'3468SLP',GETDATE(),'MABE SLP',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (27,'GISA',GETDATE(),'GISA',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (28,'GMTOL',GETDATE(),'GM TOLUCA',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (29,'VW',GETDATE(),'VW',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (30,'USIADI',GETDATE(),'ADIENT',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (31,'3433',GETDATE(),'AGC, SLP.',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (32,'0002',GETDATE(),'FAURECIA',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (33,'0003',GETDATE(),'FAURECIA, FAURECIA FRAMES, FAURECIA MECANISMOS',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (34,'USIFORDCH',GETDATE(),'FORD CHIHUAHUA',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (35,'USIFORDCU',GETDATE(),'FORD CUAUTITLAN',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (36,'3468SAL',GETDATE(),'MABE SALTILLO',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (37,'3903',GETDATE(),'MANDO CORP',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (38,'3348',GETDATE(),'PEMSA',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (39,'USIZFM',GETDATE(),'ZF EL MARQUEZ',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (40,'USIZFSR',GETDATE(),'ZF EL MARQUEZ, ZF STA ROSA',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (41,'0004',GETDATE(),'ZF SANTA ROSA',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (42,'3411SLP',GETDATE(),'FAURECIA FRAMES',1,1);
INSERT INTO cliente(id_cliente ,clave_cln, fecha_alta_cln, nombre_cln, estado_cln_id_estado, id_usuario_cln_id_usuario) VALUES (43,'3411',GETDATE(),'FAURECIA MECANISMOS',1,1);
